"""Shared versioning core for working-file history workflows."""

from .model import (
    BackupResult,
    DCC_HOUDINI,
    DCC_MAYA,
    DCC_SUBSTANCE,
    VersionOwner,
    VersionRecord,
    VersionSnapshotMember,
    VersionStreamSpec,
    normalize_text,
    stream_dirname,
    stream_filename,
    stream_key_for,
)
from .service import (
    current_version_label,
    list_version_records,
    path_matches_stream,
    resolve_working_file_version,
    restore_version,
    restored_message,
    save_version,
    saved_message,
)
from .store import (
    VERSION_MANIFEST_FILENAME,
    backup_file,
    backup_if_changed,
    current_record,
    get_manifest_path,
    load_manifest,
    next_version,
    record_publish,
    version_label,
    versioned_filename,
)

__all__ = [
    "BackupResult",
    "DCC_HOUDINI",
    "DCC_MAYA",
    "DCC_SUBSTANCE",
    "VERSION_MANIFEST_FILENAME",
    "VersionOwner",
    "VersionRecord",
    "VersionSnapshotMember",
    "VersionStreamSpec",
    "backup_file",
    "backup_if_changed",
    "current_record",
    "current_version_label",
    "get_manifest_path",
    "list_version_records",
    "load_manifest",
    "next_version",
    "normalize_text",
    "path_matches_stream",
    "record_publish",
    "resolve_working_file_version",
    "restore_version",
    "restored_message",
    "save_version",
    "saved_message",
    "stream_dirname",
    "stream_filename",
    "stream_key_for",
    "version_label",
    "versioned_filename",
]
