global proc shelf_SKD_RLO () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Open RLO File"
        -enableBackground 0
        -backgroundColor 0 0 0
        -highlightColor 0.321569 0.521569 0.65098
        -align "center"
        -label "OpenRLO"
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -imageOverlayLabel "Open RLO"
        -overlayLabelColor 2.624876 0.801436 0.012446
        -overlayLabelBackColor 0.227129 0.227129 0.227129 0.5
        -image "openLoadGeneric.png"
        -image1 "openLoadGeneric.png"
        -style "iconOnly"
        -marginWidth 0
        -marginHeight 1
        -command "from pipe.dcc.maya.shotfile import MRLOShotFileManager; fm = MRLOShotFileManager(); fm.open_file()"
        -sourceType "python"
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Create a manual version of the current RLO scene"
        -enableBackground 0
        -backgroundColor 0 0 0
        -highlightColor 0.321569 0.521569 0.65098
        -align "center"
        -label "Save Version"
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -imageOverlayLabel "Save Version"
        -overlayLabelColor 2.624876 0.801436 0.012446
        -overlayLabelBackColor 0.227129 0.227129 0.227129 0.5
        -image "save.png"
        -image1 "save.png"
        -style "iconOnly"
        -marginWidth 0
        -marginHeight 1
        -command "from pipe.dcc.maya.shotfile import MRLOShotFileManager; MRLOShotFileManager().save_version_for_current_scene()"
        -sourceType "python"
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Open version history for the current RLO scene"
        -enableBackground 0
        -backgroundColor 0 0 0
        -highlightColor 0.321569 0.521569 0.65098
        -align "center"
        -label "Version History"
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -imageOverlayLabel "Versions"
        -overlayLabelColor 2.624876 0.801436 0.012446
        -overlayLabelBackColor 0.227129 0.227129 0.227129 0.5
        -image "default.svg"
        -image1 "default.svg"
        -style "iconOnly"
        -marginWidth 0
        -marginHeight 1
        -command "from pipe.dcc.maya.shotfile import MRLOShotFileManager; MRLOShotFileManager().open_version_browser()"
        -sourceType "python"
        -commandRepeatable 1
        -flat 1
    ;
    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 38
        -enable 1
        -width 41
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Publish the current scene's camera for editorial"
        -enableBackground 0
        -backgroundColor 0 0 0
        -highlightColor 0.321569 0.521569 0.65098
        -align "center"
        -label "Publish Camera"
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -imageOverlayLabel "Publish Camera"
        -overlayLabelColor 2.624876 0.801436 0.012446
        -overlayLabelBackColor 0.227129 0.227129 0.227129 0.5
        -image "camera.closed.svg"
        -image1 "camera.closed.svg"
        -style "iconOnly"
        -marginWidth 0
        -marginHeight 1
        -command "from pipe.dcc.maya.publish import CameraPublisher; CameraPublisher().publish();"
        -sourceType "python"
        -commandRepeatable 1
        -flat 1
    ;

}
